from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = PACKAGE_ROOT.parents[1]
SOURCE_SCHEMAS = REPOSITORY_ROOT / "schemas"
PACKAGE_SCHEMAS = PACKAGE_ROOT / "src" / "benchmark_protocol" / "schemas"
GENERATED = PACKAGE_ROOT / "src" / "benchmark_protocol" / "generated"


def generate(destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    models: dict[Path, bytes] = {}
    versions = sorted(
        (path for path in SOURCE_SCHEMAS.iterdir() if path.is_dir()),
        key=lambda path: tuple(int(part) for part in path.name.split(".")),
    )
    codegen = shutil.which("datamodel-codegen")
    if codegen is None:
        raise RuntimeError("datamodel-codegen is unavailable")
    for version in versions:
        with tempfile.TemporaryDirectory() as temporary:
            generated = Path(temporary) / "generated"
            # Security proof: generation requires the pinned CLI; its executable is absolute,
            # every argument is repository-owned, and shell=False.
            subprocess.run(  # noqa: S603
                [
                    codegen,
                    "--input",
                    str(version),
                    "--input-file-type",
                    "jsonschema",
                    "--output",
                    str(generated),
                    "--output-model-type",
                    "typing.TypedDict",
                    "--target-python-version",
                    "3.12",
                    "--use-standard-collections",
                    "--use-union-operator",
                    "--disable-timestamp",
                ],
                check=True,
                shell=False,
            )
            for source in generated.rglob("*.py"):
                if source.name == "__init__.py":
                    continue
                models[source.relative_to(generated)] = source.read_bytes()
    for relative, content in models.items():
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    for directory in [destination, *(path for path in destination.rglob("*") if path.is_dir())]:
        (directory / "__init__.py").write_text(
            "# generated by datamodel-codegen from versioned schemas\n",
            encoding="utf-8",
        )


def same_files(left: Path, right: Path) -> bool:
    left_files = {
        path.relative_to(left): path.read_bytes() for path in left.rglob("*") if path.is_file()
    }
    right_files = (
        {path.relative_to(right): path.read_bytes() for path in right.rglob("*") if path.is_file()}
        if right.exists()
        else {}
    )
    return left_files == right_files


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as temporary:
        candidate = Path(temporary) / "generated"
        generate(candidate)
        if args.check:
            if not same_files(candidate, GENERATED) or not same_files(
                SOURCE_SCHEMAS, PACKAGE_SCHEMAS
            ):
                raise SystemExit("generated Python models are stale; run the generator")
        else:
            shutil.rmtree(GENERATED, ignore_errors=True)
            shutil.copytree(candidate, GENERATED)
            shutil.rmtree(PACKAGE_SCHEMAS, ignore_errors=True)
            shutil.copytree(SOURCE_SCHEMAS, PACKAGE_SCHEMAS)
            shutil.copy2(
                REPOSITORY_ROOT / "VERSION", PACKAGE_ROOT / "src" / "benchmark_protocol" / "VERSION"
            )


if __name__ == "__main__":
    main()
